"""initial migration

Revision ID: fe325af46749
Revises: 6efde7cdb473
Create Date: 2026-07-28 16:15:23.404221

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "fe325af46749"
down_revision: Union[str, Sequence[str], None] = "6efde7cdb473"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("number", sa.String(length=20), nullable=False)
    )
    op.add_column(
        "users", sa.Column("first_name", sa.String(length=20), nullable=False)
    )
    op.add_column(
        "users", sa.Column("second_name", sa.String(length=20), nullable=False)
    )
    op.add_column(
        "users", sa.Column("sex", sa.String(length=10), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "sex")
    op.drop_column("users", "second_name")
    op.drop_column("users", "first_name")
    op.drop_column("users", "number")
    # ### end Alembic commands ###
